name: Deploy to Surge

on:
  workflow_dispatch:
  push:
    branches: "surge"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages"
  cancel-in-progress: true 
jobs:
  buildNdeploy: 
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash 
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy to Surge
        run: |
         npm install -g surge
         surge ./dist --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 