name: Deploy to GitHub Pages

# déclenche le déploiement à chaque push
on:
  workflow_dispatch:
  push:
    branches: "main"

# définition des permissions et autorisations afin de permettre le déploiement sur github pages
permissions:
  contents: read
  pages: write
  id-token: write

# autorise un déploiement à la fois
concurrency: 
  group: "pages"
  cancel-in-progress: true 
jobs:
  build: 
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash 
        working-directory: ./app
    steps:
      # fetch code
      - name: Checkout
        uses: actions/checkout@v3
      # installation des librairies
      - name: Install dependencies
        run: npm ci
      # build website
      - name: Build
        run: npm run build
      # upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: ./app/dist
          name: artifact
  # deploy to github pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.6
        id: pages
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.9
        with:
          artifact_name: artifact